apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chdb-pvc
  namespace: ns-channel
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ns-db-local
  resources:
    requests:
      storage: 10Gi
